### ISSUE TITLE
Double-counting consecutive overlaps?

### ISSUE THREAD

**Issue by jessjaco** [digitalearthpacific/dep-coastlines#9]
Consider that now since we are pulling all data within a tile footprint we may have consecutive overlaps which are biasing median (and other) calcs.

**Comment by alexgleith** [comment]
What do you mean by consecutive overlaps?

The same scene twice?

**Comment by jessjaco** [comment]
Adjacent scenes on a path which are taken consecutively on the same day, like these 
![image](https://github.com/digitalearthpacific/dep-coastlines/assets/1250693/2c059c33-cc12-4432-84f1-842c32a05ce0)

**Comment by alexgleith** [comment]
Got it.

This is the kind of the the Open Data Cube is really good at.

I know it's late in the process, but it might be worth exploring the use of ODC STAC instead of STAC Stack: https://odc-stac.readthedocs.io/en/latest/

This loads data based on STAC items, but it'll do it in a way where the adjacent scenes are carefully overlaid.

Another little thing that might make a big difference is in picking a CRS. I saw were using an Equal Earth projection, but Robbi picks the most common UTM projection. I know he found better results when not using regridded data over Australia. The effects will likely be very minor, though.

**Comment by jessjaco** [comment]
I don't think using `groupby=solar_day` in the odc.stac.load is going to work, as we need the exact times for tidal filtering. Will think about whether it's possible to stage the steps in another way

**Comment by alexgleith** [comment]
Check in with Robbi on that one.

I think groupby solar day is good though, as the images are captured as a swath so are basically at the same time.

It means you get a single slice for each day, rather than it being broken up by scenes, I think.
